---
driver:
  name: vagrant
  driver_config:
    ssl_verify_mode: ":verify_none"

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  galaxy_ignore_certs: true
  roles_path: spec/ansible/nginx-hardening
  requirements_path: spec/ansible/nginx-hardening/requirements.yml
  additional_copy_path:
    - spec/ansible/nginx-hardening/vars
  extra_vars_file: /tmp/kitchen/vars/vagrant.vars.yml

verifier:
  name: inspec
  sudo: true
  load_plugins: true
  inspec_tests:
    - path: .
  # controls:
  #   - "<%= ENV['INSPEC_CONTROL'] %>"

platforms:
  - name: ubuntu-18.04
    lifecycle:
      post_create:
        - remote: sudo apt-get -y update
        - remote: sudo apt-get -y install nginx apt-utils
        - remote: sudo systemctl start nginx
suites:
  - name: hardened
    provisioner:
      playbook: spec/ansible/nginx-hardening/hardening-playbook.yml
    verifier:
      reporter:
        - cli
        - json:spec/results/hardened-test-result.json
  - name: vanilla
    provisioner:
      playbook: spec/ansible/nginx-hardening/vanilla-playbook.yml
    verifier:
      reporter:
        - cli
        - json:spec/results/vanilla-test-result.json
