---
driver:
  name: vagrant
  driver_config:
    ssl_verify_mode: ":verify_none"

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  roles_path: spec/ansible/nginx-hardening
  requirements_path: spec/ansible/nginx-hardening/requirements.yml
  galaxy_ignore_certs: true

verifier:
  name: inspec
  sudo: true
  load_plugins: true
  inspec_tests:
    - path: .

platforms:
  - name: ubuntu-18.04
    lifecycle:
      post_create:
        - remote: sudo apt-get -y update
        - remote: sudo apt-get -y install nginx apt-utils
        - remote: sudo systemctl start nginx
        - remote: sudo ufw app list
        - remote: sudo ufw allow 'Nginx HTTP'
        - remote: sudo ufw status
        - remote: systemctl status nginx
suites:
  - name: hardened
    provisioner:
      playbook: spec/ansible/nginx-hardening/hardening-playbook.yml
    verifier:
      reporter:
        - cli
        - json:spec/results/hardened-test-result.json
  - name: vanilla
    provisioner:
      playbook: spec/ansible/nginx-hardening/vanilla-playbook.yml
    verifier:
      reporter:
        - cli
        - json:spec/results/vanilla-test-result.json
