---
driver:
  name: docker
  use_sudo: false
  privileged: true

transport:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true
  roles_path: spec/ansible/nginx-hardening
  requirements_path: spec/ansible/nginx-hardening/requirements.yml
  galaxy_ignore_certs: true

verifier:
  name: inspec
  sudo: true
  load_plugins: true
  inspec_tests:
    - path: .

platforms:
  - name: debian10-nginx-latest
    driver:
      image: nginx:latest
      platform: debian
      provision_command:
        - apt update
        - apt install -y systemd-sysv
        - systemctl enable ssh.service

suites:
  - name: hardened
    provisioner:
      playbook: spec/ansible/nginx-hardening/hardening-playbook.yml
    verifier:
      reporter:
        - cli
        - json:spec/results/hardened-test-result.json
  - name: vanilla
    provisioner:
      playbook: spec/ansible/nginx-hardening/vanilla-playbook.yml
    verifier:
      reporter:
        - cli
        - json:spec/results/vanilla-test-result.json
