# encoding: UTF-8

control "V-41818" do
  title "The web server must accept only system-generated session identifiers."
  desc  "Communication between a client and the web server is done using the
HTTP protocol, but HTTP is a stateless protocol. In order to maintain a
connection or session, a web server will generate a session identifier (ID) for
each client session when the session is initiated. The session ID allows the
web server to track a user session and, in many cases, the user, if the user
previously logged into a hosted application.

    When a web server accepts session identifiers that are not generated by the
web server, the web server creates an environment where session hijacking, such
as session fixation, could be used to access hosted applications through
session IDs that have already been authenticated. Forcing the web server to
only accept web server-generated session IDs and to create new session IDs once
a user is authenticated will limit session hijacking.
  "
  desc  "rationale", ""
  desc  "check", "
  Review the web server documentation and deployed configuration to determine
  whether the web server accepts session IDs that are not system-generated.

  If it is determined that the web server is not required to perform session management, 
  this check is Not Applicable. 

  Nginx web server versions after 1.11.0 have the $request_id embedded variable by default. 
  This variable is a unique request identifier generated from 16 random bytes, in hexadecimal. 

  Execute the following command to get the current version of Nginx running:
    # nginx -v

  If the current version of Nginx running is 1.11.0 or earlier, this is a finding. 
  "
  desc  "fix", "Upgrade to the lastest stable version of Nginx web server to use the '$request_id' 
  embedded variable for generating unique identifers."

  impact 0.5
  tag "severity": "medium"
  tag "gtitle": "SRG-APP-000223-WSR-000145"
  tag "gid": "V-41818"
  tag "rid": "SV-54395r3_rule"
  tag "stig_id": "SRG-APP-000223-WSR-000145"
  tag "fix_id": "F-47277r3_fix"
  tag "cci": ["CCI-001664"]
  tag "nist": ["SC-23 (3)", "Rev_4"]

# Nginx versions after 1.11.0 have the $request_id embedded variable by default
# This variable is a unique request identifier generated from 16 random bytes, in hexadecimal

  describe nginx do
    its('version') { should cmp > '1.11.0' }
  end
  
end

