# encoding: UTF-8

control "V-55977" do
  title "The NGINX web server must record time stamps for log records to a minimum
granularity of one second."
  desc  "Without sufficient granularity of time stamps, it is not possible to
adequately determine the chronological order of records.

    Time stamps generated by the web server include date and time and must be
to a granularity of one second.
  "
  
  desc  "check", "Review the NGINX web server documentation and configuration to
  determine if log records are time stamped to a minimum granularity of one second.

  Check for the following:
      # grep for a 'log_format' directive in the http context of the nginx.conf.

  If the 'log_format' directive is not configured to contain the '$time_local' 
  variable, this is a finding. 
  "
  desc  "fix", "Configure the 'log_format' directive in the nginx.conf to use the 
  '$time_local' variable to record log events with a time stamp to a granularity 
  of one second."

  impact 0.5
  tag "severity": "medium"
  tag "gtitle": "SRG-APP-000375-WSR-000171"
  tag "gid": "V-55977"
  tag "rid": "SV-70231r2_rule"
  tag "stig_id": "SRG-APP-000375-WSR-000171"
  tag "fix_id": "F-60855r1_fix"
  tag "cci": ["CCI-001889"]
  tag "nist": ["AU-8 b", "Rev_4"]

  # log_format - Context:	http
  nginx_conf.params['http'].each do |http|
    http["log_format"].each do |log_format|
      describe 'time_local' do
        it 'should be part of every log format in the http context.' do
          expect(log_format.to_s).to(match /.*?\$time_local.*?/)
        end
      end
    end
  end  
end

