# encoding: UTF-8
conf_path = input('conf_path')
mime_type_path = input('mime_type_path')
access_log_path = input('access_log_path')
error_log_path = input('error_log_path')
password_path = input('password_path')
key_file_path = input('key_file_path')

control "V-55977" do
  title "The web server must record time stamps for log records to a minimum
granularity of one second."
  desc  "Without sufficient granularity of time stamps, it is not possible to
adequately determine the chronological order of records.

    Time stamps generated by the web server include date and time and must be
to a granularity of one second.
  "
  desc  "rationale", ""
  desc  "check", "
    Review the web server documentation and configuration to determine if log
records are time stamped to a minimum granularity of one second.

    Have a user generate a logable event and review the log data to determine
if the web server is configured correctly.

    If the log data does not contain a time stamp to a minimum granularity of
one second, this is a finding.
  "
  desc  "fix", "Configure the web server to record log events with a time stamp
to a granularity of one second."
  impact 0.5
  tag "severity": "medium"
  tag "gtitle": "SRG-APP-000375-WSR-000171"
  tag "gid": "V-55977"
  tag "rid": "SV-70231r2_rule"
  tag "stig_id": "SRG-APP-000375-WSR-000171"
  tag "fix_id": "F-60855r1_fix"
  tag "cci": ["CCI-001889"]
  tag "nist": ["AU-8 b", "Rev_4"]

  describe "Skip Test" do
    skip "This is a manual check"
  end
  
end

